### ISSUE TITLE
Please document default setting of `xmlns` option

### ISSUE THREAD

**Issue by rrthomas** [wvbe/slimdom-sax-parser#27]
`slimdom-sax-parser` sets `xmlns: true`, which is undocumented, and confused me when I realised that my `additionalNamespaces` setting should not be working according to the `saxes` docs: `xmlns` defaults to `false` in saxes, and the docs say: "Of course, additionalNamespaces and resolvePrefix are used only if xmlns is true."

**Comment by wvbe** [comment]
Updated the README with a short note on this, will also be pushed to npmjs.org on the next release. I think that means the ticket is done, so I'll close it soon unless it turns out I made a boo-boo

**Comment by rrthomas** [comment]
LGTM, thanks!
